export const Colors = {
  primary: "#F6F6F6",
  red: "#E93D3D",
  gray: "#EAEAEA",
  green: "#4DCA61",
  frontend: "#F7DF1E",
  mobile: "#222222",
  backend: "#660A0E",
  grayText: "#6B6B6B",
  background: "#FFFFFF",
  chatBotBack: "#FFFFFF",
  chatBotColor: "#808080",
  chatUserBack: "#A9F1C1",
  chatUserColor: "#231F20",
  chatUserQuickBack: "#FFFFFF",
  chatUserQuickBorder: "#0645AD",
  chatQuickReply: "",
  chatQuickReplyColor: "",
};
