export const AUTHENTICATED_FIREBASE = "AUTHENTICATED_FIREBASE";
export const AUTHENTICATED_SERVER = "AUTHENTICATED_SERVER";

export const AUTHENTICATED_FIREBASE_AND_SERVER =
  "AUTHENTICATED_FIREBASE_AND_SERVER";
